test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    # https://github.com/docker/compose/issues/5696
    COMPOSE_INTERACTIVE_NO_CLI: 1
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose up -d
  script:
    - docker-compose exec -T drupal composer install -n --prefer-dist
    - docker-compose exec -T drupal vendor/bin/parallel-lint src tests
    - docker-compose exec -T drupal vendor/bin/phpcs --report-full
    - docker-compose exec -T drupal vendor/bin/drush si -yv --db-url=mysql://circle:circle@db/circle --account-name=admin --account-pass=password standard
    - docker-compose exec -T drupal chown -R www-data:www-data .
    - docker-compose exec -T drupal vendor/bin/phpunit --debug --colors --bootstrap=web/core/tests/bootstrap.php tests
